name: Healthcheck

on:
  schedule:
    # - cron: "*/5 * * * *"
    - cron: "0 0 * * *"

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://pokedex911.herokuapp.com/health
          follow-redirect: false 
          max-attempts: 3
          retry-delay: 10s 
          retry-all: false
